module.exports = {
  notificacaoModelo: {
    id: '476f90b1-492b-495f-9630-1cbf606a1f00',
    userId: 'notificacao-userId',
    unidadeSaudeId: 'notificacao-unidadeSaudeId',
    notificadorId: 'notificacao-notificadorId',
    bairroId: 'notificacao-bairroId',
    pessoaId: 'notificacao-pessoaId',
    profissaoId: 'notificacao-profissaoId',
    nomeNotificador: 'FRANCISCO THIAGO DE ALMEIDA DOS SANTOS SILVA E ANATÁSIO TERCEIRO DE MELO JUNIOR',
    status: 'ABERTA',
    municipioId: 'notificacao-municipioId',
    createdAt: '2020-05-02T21:32:42.515Z',
    updatedAt: '2020-05-02T21:32:42.515Z',
    Pessoa: {
      id: 'notificacao-pessoa-id',
      nome: 'NOME COMPLETO A  C DA PESSOAA',
      dataDeNascimento: '1994-04-08',
      sexo: 'F',
      idade: null,
      numeroDocumento: '32201501874',
      tipoDocumento: 'RG',
      nomeDaMae: 'NOME DA MAE',
      ocupacao: 'DESCRICAO DA OCUPACAO',
      endereco: 'ENDERECO',
      numero: '545445',
      bairroId: 'notificacao-pessoa-bairroId',
      municipioId: 'notificacao-pessoa-municipioId',
      telefoneResidencial: '4430355965',
      telefoneContato: '4430356985',
      telefoneCelular: '44996546456',
      gestante: 'NAO_APLICADO',
      racaCor: 'PRETA',
      complemento: 'COMPLEMENTO',
      ocupacaoId: 'pessoa-ocupacaoId',
      tipoClassificacaoPessoa: 'OUTRO',
      cep: '',
      createdAt: '2020-05-01T03:11:58.446Z',
      updatedAt: '2020-05-01T03:11:58.446Z',
      Bairro: {
        id: 'pessoa-bairro-Id',
        nome: 'notificacao-pessoa-bairro-nome',
        municipioId: 'notificacao-pessoa-bairro-municipioId',
        createdAt: '2020-04-27T00:13:56.563Z',
        updatedAt: '2020-04-27T00:13:56.563Z',
      },
      Municipio: {
        id: 'pessoa-municipioId',
        nome: 'MARINGA',
        uf: 'PR',
        createdAt: '2020-04-27T00:13:56.465Z',
        updatedAt: '2020-04-27T00:13:56.465Z',
      },
      Ocupacao: {
        id: 'pessoa-ocupacaoId',
        descricao: 'Trabalhador/Profissional de Saúde',
        classificacao: '',
        createdAt: '2020-04-27T00:13:58.109Z',
        updatedAt: '2020-04-27T00:13:58.109Z',
      },
    },
    NotificacaoCovid19: {
      id: 'ca477a66-6f17-43a8-8abb-6f38d099b4b3',
      notificacaoId: 'notificacao-notificacaoCovid19-notificacaoId',
      sintomatico: true,
      dataInicioDosSintomas: '2020-04-28',
      dataHoraNotificacao: '2020-04-29T01:41:00.000Z',
      coriza: false,
      tosse: false,
      dorDeGarganta: false,
      mialgia: false,
      escarro: false,
      sibilo: false,
      batimentoAsasNasais: false,
      dispneia: false,
      taquipneia: false,
      tiragemIntercostal: false,
      saturacaoDeOximetriaDePulso: false,
      cianoseCentral: false,
      febreAferidaReferida: false,
      temperaturaFebre: '45',
      congestaoNasal: false,
      diminuicaoDePulsoPeriferico: false,
      hipotensao: false,
      diarreia: false,
      adinamiaFraqueza: false,
      artralgia: false,
      calafrios: false,
      conjuntivite: false,
      dificuldadeDeglutir: false,
      gangliosLinfaticos: false,
      irritabilidadeConfusao: false,
      manchasVermelhas: false,
      cefaleia: false,
      nauseaVomito: false,
      outrosSintomas: null,
      puerperaAte45DiasDoParto: false,
      sindromeDeDown: false,
      diabetesMellitus: false,
      imunodeficiencia: false,
      doencaCardioVascularCronica: false,
      doencaHepaticaCronica: false,
      doencaNeurologicaCronica: false,
      doencaRenalCronica: false,
      doencaHematologicaCronica: false,
      asma: false,
      hipertensao: false,
      infeccaoHIV: false,
      neoplasia: false,
      tabagismo: false,
      outraPneumopatiaCronica: false,
      obesidade: false,
      outrosComorbidades: 'OUTROS RISCOS',
      tamiflu: true,
      hidroxicloroquina: true,
      nomeMedicamento: 'ESPECIFIQUE MEDICAMENTO',
      historicoDeViagem: true,
      dataDaViagem: '2020-04-28',
      localDaViagem: 'LOCAL DA VIAGEM',
      recebeuVacinaDaGripeNosUltimosDozeMeses: 'NAO',
      situacao1: true,
      situacao2: false,
      nomeTeveContato: 'NOME TEVE CONTATO',
      coletaMaterialParaDiagnostico: true,
      tipoLaboratorio: 'PRIVADO',
      nomeLaboratorioEnvioMaterial: 'REDE PRIVADA',
      dataDaColeta: '2020-04-28 00:00:00.000 +00:00',
      metodoDeExame: 'TESTE_RAPIDO',
      realizouExameDeImagem: true,
      raioXNormal: true,
      raioXInfiltrado: false,
      raioXConsolidacao: false,
      raioXMisto: false,
      raioXOutro: '',
      tomografiaNormal: false,
      tomografiaVitro: true,
      tomografiaDerrame: true,
      tomografiaLinfonodo: true,
      tomografiaOutro: 'OUTRA TOMOGRAFIA',
      observacoes: 'OBSERVACOES',
      contatoComSuspeito: 'SUSPEITO',
      localDoContatoComSuspeito: 'DOMICILIO',
      localDoContatoComSuspeitoOutro: null,
      nomeSuspeito: 'NOME DA PESSOA',
      situacaoNoMomentoDaNotificacao: 'ALTA_ISOLAMENTO_DOMICILIAR',
      createdAt: '2020-05-02T21:32:42.877Z',
      updatedAt: '2020-05-02T21:32:42.877Z',
    },
    Bairro: {
      id: 'notificacao-bairro-id',
      nome: 'notificacao-bairro-nome',
      municipioId: 'notificacao-bairro-municipioId',
      createdAt: '2020-04-27T00:13:56.563Z',
      updatedAt: '2020-04-27T00:13:56.563Z',
    },
    Municipio: {
      id: 'notificacao-municipio-id',
      nome: 'MARINGA',
      uf: 'PR',
      createdAt: '2020-04-27T00:13:56.465Z',
      updatedAt: '2020-04-27T00:13:56.465Z',
    },
    UnidadeSaude: {
      id: 'notificacao-unidadeSaude-id',
      nome: 'HOSPITAL UNIVERSITARIO REGIONAL DE MARINGA',
      municipioId: 'ac3227a1-8a09-4b5f-93cd-d6ca43b637a2',
      cnes: '2587335',
      createdAt: '2020-04-27T00:13:56.688Z',
      updatedAt: '2020-04-27T00:13:56.688Z',
    },
    User: {
      id: 'notificacao-user-id',
      email: 'notificador@notificasaude.com.br',
      createdAt: '2020-04-27T00:13:56.922Z',
      updatedAt: '2020-04-27T00:13:56.922Z',
    },
    ProfissionalSaude: {
      id: 'notificacao-profissionalSaude-id',
      nome: 'NOTIFICADOR',
      email: 'notificador@notificasaude.com.br',
      profissao: 'ENFERMEIRO',
      unidadesaudeId: 'ac3227a1-8a09-4b5f-93cd-d6ca43b637a3',
      createdAt: '2020-04-27T00:13:56.839Z',
      updatedAt: '2020-04-27T00:13:56.839Z',
    },
    Profissao: {
      id: 'notificacao-profissao-id',
      nome: 'ENFERMEIRO',
      createdAt: '2020-04-27T00:13:56.349Z',
      updatedAt: '2020-04-27T00:13:56.349Z',
    },
  },
  notificacaoMapeadoResponse: {
    id: '476f90b1-492b-495f-9630-1cbf606a1f00',
    dataHoraNotificacao: '2020-04-29T01:41:00.000Z',
    unidadeSaudeId: 'notificacao-unidadeSaudeId',
    unidadeSaudeNome: 'HOSPITAL UNIVERSITARIO REGIONAL DE MARINGA',
    notificadorId: 'notificacao-notificadorId',
    sintomatico: true,
    realizouExamesImagem: true,
    dataInicioDosSintomas: '2020-04-28',
    userId: 'notificacao-userId',
    nomeNotificador: 'FRANCISCO THIAGO DE ALMEIDA DOS SANTOS SILVA E ANATÁSIO TERCEIRO DE MELO JUNIOR',
    profissaoId: 'notificacao-profissaoId',
    tipoDeContatoComCaso: 'SUSPEITO',
    tipoDeLocalDoCaso: 'DOMICILIO',
    nomeDoCaso: 'NOME DA PESSOA',
    observacoes: 'OBSERVACOES',
  },
  suspeitoMapeadoResponse: {
    pessoaId: 'notificacao-pessoa-id',
    tipoDocumento: 'RG',
    numeroDocumento: '32201501874',
    nome: 'NOME COMPLETO A  C DA PESSOAA',
    dataDeNascimento: '1994-04-08',
    sexo: 'F',
    cep: '',
    bairroId: 'notificacao-pessoa-bairroId',
    bairro: 'notificacao-pessoa-bairro-nome',
    nomeDaMae: 'NOME DA MAE',
    ocupacao: 'DESCRICAO DA OCUPACAO',
    ocupacaoId: 'pessoa-ocupacaoId',
    endereco: 'ENDERECO',
    numero: '545445',
    complemento: 'COMPLEMENTO',
    municipioId: 'notificacao-pessoa-bairro-municipioId',
    municipio: 'MARINGA',
    telefoneResidencial: '4430355965',
    telefoneContato: '4430356985',
    telefoneCelular: '44996546456',
    racaCor: 'PRETA',
    tipoClassificacaoPessoa: 'OUTRO',
    uf: 'PR',
    idade: null,
    gestante: 'NAO_APLICADO',
  },
  sintomasMapeadoResponse: {
    febreAferidaReferida: false,
    temperaturaFebre: '45',
    adinamiaFraqueza: false,
    artralgia: false,
    calafrios: false,
    conjuntivite: false,
    coriza: false,
    congestaoNasal: false,
    dificuldadeDeglutir: false,
    gangliosLinfaticos: false,
    irritabilidadeOuConfusao: false,
    manchasVermelhas: false,
    tosse: false,
    dorDeGarganta: false,
    mialgia: false,
    escarro: false,
    sibilo: false,
    batimentoAsasNasais: false,
    dispneia: false,
    taquipneia: false,
    saturacaoDeOximetriaDePulso: false,
    cianoseCentral: false,
    diminuicaoDePulsoPeriferico: false,
    hipotensao: false,
    diarreia: false,
    cefaleia: false,
    nauseaVomito: false,
    tiragemIntercostal: false,
    outros: null,
  },
  comorbidadesMapeadoResponse: {
    puerperaAte45DiasDoParto: false,
    sindromeDeDown: false,
    diabetesMellitus: false,
    imunodeficiencia: false,
    doencaCardioVascularCronica: false,
    doencaHepaticaCronica: false,
    doencaNeurologicaCronica: false,
    doencaRenalCronica: false,
    doencaHematologicaCronica: false,
    asma: false,
    outraPneumopatiaCronica: false,
    obesidade: false,
    hipertensao: false,
    infeccaoHIV: false,
    neoplasia: false,
    tabagismo: false,
    outros: 'OUTROS RISCOS',
  },
  examesImagemMapedoResponse: {
    raioNormal: true,
    raioInfiltradoIntersticial: false,
    raioConsolidacao: false,
    raioMisto: false,
    raioOutro: '',
    tomografiaNormal: false,
    tomografiaVidroFoscoPredominioPerifericoBasal: true,
    tomografiaAusenciaDerramePleural: true,
    tomografiaAusenciaLinfonodoMediastenal: true,
    tomografiaOutro: 'OUTRA TOMOGRAFIA',
  },
  informacaoComplementarMapeadoResponse: {
    tamiflu: true,
    hidroxicloroquina: true,
    nomeMedicamento: 'ESPECIFIQUE MEDICAMENTO',
    historicoDeViagem: true,
    dataDaViagem: '2020-04-28',
    localDaViagem: 'LOCAL DA VIAGEM',
    recebeuVacinaDaGripeNosUltimosDozeMeses: 'NAO',
  },
  vinculoEpidemiologicoMapeadoResponse: {
    situacao1: true,
    situacao2: false,
    nome: 'NOME TEVE CONTATO',
  },
  conclusaoAtendimentoMapeadoResponse: {
    situacaoNoMomentoDaNotificacao: 'ALTA_ISOLAMENTO_DOMICILIAR',
    coletaMaterialParaDiagnostico: true,
    tipoLaboratorio: 'PRIVADO',
    nomeLaboratorioEnvioMaterial: 'REDE PRIVADA',
    dataDaColeta: '2020-04-28 00:00:00.000 +00:00',
    metodoDeExame: 'TESTE_RAPIDO',
  },
};
