module.exports = {
    userId: "ecbc9391-f49e-47b8-a4b2-54512db60343",
    unidadeSaudeId: "90335cf3-6b82-4b84-9cb5-3f7a99000c1e",
    notificadorId: "e1eddb03-8e61-4911-b554-1147e787ac01",
    municipioId: "53953789-76cb-40eb-a485-fe2d84072dd5",
    pessoaId: "eb83e151-1b4f-4ef5-af88-5fea4d16bc1a",
    bairroId: "22144d3e-5921-4827-9bac-53243d2ff629",
    profissaoId: "53b8082e-59e5-44fb-b1d1-dcc98a022e1c",
    nomeNotificador: "FRANCISCO THIAGO DE ALMEIDA DOS SANTOS SILVA E ANATÁSIO TERCEIRO DE MELO JUNIOR",
    status: undefined,
    notificacaoCovid19: {
        sintomatico: true,
        dataInicioDosSintomas: "2020-04-28",
        dataHoraNotificacao: "2020-04-29T01:41:00.000Z",
        febreAferidaReferida: false,
        temperaturaFebre: "45",
        artralgia: false,
        calafrios: false,
        conjuntivite: false,
        coriza: false,
        congestaoNasal: false,
        dificuldadeDeglutir: false,
        gangliosLinfaticos: false,
        tosse: false,
        dorDeGarganta: false,
        mialgia: false,
        escarro: false,
        sibilo: false,
        batimentoAsasNasais: false,
        dispneia: false,
        taquipneia: false,
        saturacaoDeOximetriaDePulso: false,
        cianoseCentral: false,
        diminuicaoDePulsoPeriferico: false,
        hipotensao: false,
        diarreia: false,
        cefaleia: false,
        nauseaVomito: false,
        tiragemIntercostal: false,
        existemOutrosSintomas: true,
        adinamiaFraqueza: false,
        irritabilidadeConfusao: false,
        manchasVermelhas: false,
        outrosSintomas: null,
        puerperaAte45DiasDoParto: false,
        sindromeDeDown: false,
        diabetesMellitus: false,
        imunodeficiencia: false,
        doencaCardioVascularCronica: false,
        doencaHepaticaCronica: false,
        doencaNeurologicaCronica: false,
        doencaRenalCronica: false,
        doencaHematologicaCronica: false,
        asma: false,
        outraPneumopatiaCronica: false,
        obesidade: false,
        hipertensao: false,
        infeccaoHIV: false,
        neoplasia: false,
        tabagismo: false,
        outrasComorbidades: true,
        outrosComorbidades: "OUTROS RISCOS",
        tamiflu: true,
        hidroxicloroquina: true,
        nomeMedicamento: "ESPECIFIQUE MEDICAMENTO",
        historicoDeViagem: true,
        dataDaViagem: "2020-04-28",
        localDaViagem: "LOCAL DA VIAGEM",
        recebeuVacinaDaGripeNosUltimosDozeMeses: "NAO",
        situacao1: true,
        situacao2: false,
        nomeTeveContato: "",
        situacaoNoMomentoDaNotificacao: "ALTA_ISOLAMENTO_DOMICILIAR",
        coletaMaterialParaDiagnostico: true,
        tipoLaboratorio: "PRIVADO",
        nomeLaboratorioEnvioMaterial: "REDE PRIVADA",
        dataDaColeta: "2020-04-28",
        metodoDeExame: "TESTE_RAPIDO",
        raioXNormal: true,
        raioXInfiltrado: false,
        raioXConsolidacao: false,
        raioXMisto: false,
        raioXOutro: "",
        tomografiaNormal: false,
        tomografiaVitro: true,
        tomografiaDerrame: true,
        tomografiaLinfonodo: true,
        tomografiaOutro: "OUTRA TOMOGRAFIA",
        observacoes: "OBSERVACOES",
        contatoComSuspeito: "SUSPEITO",
        localDoContatoComSuspeito: "DOMICILIO",
        nomeSuspeito: "NOME DA PESSOA",
        realizouExameDeImagem: true
    }
}